version: "3.8"

services:
  fhir-db:
    image: postgres:15
    environment:
      POSTGRES_DB: hapi
      POSTGRES_USER: hapi
      POSTGRES_PASSWORD: hapi123
    volumes:
      - fhir-pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  fhir-server:
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://fhir-db:5432/hapi
      spring.datasource.username: hapi
      spring.datasource.password: hapi123
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hapi.fhir.fhir_version: R4
      hapi.fhir.allow_multiple_delete: "true"
      hapi.fhir.validation.requests_enabled: "true"
      hapi.fhir.implementationguides.uscore.packageUrl: "https://packages.simplifier.net/hl7.fhir.us.core/6.1.0"
      hapi.fhir.implementationguides.uscore.name: "hl7.fhir.us.core"
      hapi.fhir.implementationguides.uscore.version: "6.1.0"
      hapi.fhir.implementationguides.uscore.installMode: STORE_AND_INSTALL
      hapi.fhir.implementationguides.cdcrec.packageUrl: "https://packages.simplifier.net/hl7.terminology.r4/6.2.0"
      hapi.fhir.implementationguides.cdcrec.name: "hl7.terminology.r4"
      hapi.fhir.implementationguides.cdcrec.version: "6.2.0"
      hapi.fhir.implementationguides.cdcrec.installMode: STORE_AND_INSTALL
    depends_on:
      - fhir-db

volumes:
  fhir-pgdata:
